### ISSUE TITLE
Strip prefix on dispatch?

### ISSUE THREAD

**Issue by kelunik** [amphp/http-server-router#3]
Should we strip the defined prefix when dispatching requests, so the routes get the URI as defined? The original use case for prefixing was to be able to have modules, which can be deployed under a single origin and all have their own router, such as https://www.google.com/chrome/ basically being its own site below https://www.google.com/.

**Comment by bwoebi** [comment]
The code needs to be able to be aware of being prefixed and looking at the provided URI is a way to do that.

**Comment by kelunik** [comment]
Closing, this should be done with a middleware.
