### ISSUE TITLE
Should middleware also be run for the fallback route?

### ISSUE THREAD

**Issue by PeeHaa** [amphp/http-server-router#8]
It seems like middleware are not ran when the fallback route is hit. This should probably be fixed.

**Comment by PeeHaa** [comment]
The session middleware is never executed for the fallback. It works just fine when going through an actual defined route.

```php
$router = new Router();

$router->addRoute('GET', '/ws', $this->auryn->make(WebSocket::class));

$router->setFallback($this->auryn->make(FrontController::class));
$router->stack($this->auryn->make(SessionMiddleware::class));

$server = new Server($this->getServerSockets(), $router, $logger);
```

**Comment by kelunik** [comment]
This is kinda by design, because the fallback was mostly intended to be used for static assets, and you don't want things like the `SessionMiddleware` being active for your static assets.

It's pretty easy to add the same stack to the fallback, but it's way harder to skip a middleware if you don't want it to apply to the fallback.

**Comment by PeeHaa** [comment]
How hard is it/how stupid an idea is it to process middleware for fallback, but not for `DocumentRoot` handler instead?

**Comment by kelunik** [comment]
I don't understand what you mean.

**Comment by PeeHaa** [comment]
Instead of not executing middleware for the fallback only skip the middleware for *specific* handlers in fallback (like the DocumentRoot one)

**Comment by kelunik** [comment]
No, that's not possible, because the router would be tightly coupled to these and as soon as you wrap a handler with a middleware, you have a different handler and the router won't see the original handler anymore.
